name: Backend Deploy

on:
  push:
    branches: [ master ]
    paths:
      - "python-part/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull latest code & restart backend
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e
            cd ~/fetch-1-dot-tongji
            git fetch origin
            git reset --hard origin/master
            cd python-part
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart dotB.service
          EOF
